### ISSUE TITLE
Ability to send Manufacturer, Model, etc during Add Call.

### ISSUE THREAD

**Issue by brannon-bowden** [cflurin/homebridge-websocket#11]
It appears that sending in additional information such as Mfg,Model, etc during the add process is not supported (like it is in your mqtt plugin). Would it be possible to get it added to this project as well?

**Comment by brannon-bowden** [comment]
Even if something was hardcoded in the source code, it would help tons. (Trying to distinguish between devices added by this plugin and other plugins via the rest api).

**Comment by cflurin** [comment]
Hi,
For the homebridge-mqtt plugin I got a [PR](https://github.com/cflurin/homebridge-mqtt/pull/48)
If you like, you can try to add this feature, a PR for the `homebridge-websocket` would be great.

**Comment by brannon-bowden** [comment]
I'll have a look, my javascript skills are weak unfortunately, and I am still trying to understand the structure of the plugins. Will see what I can do.

**Comment by cflurin** [comment]
Hi,
Thanks for your PR.
I've just published version 0.2.0.
