### ISSUE TITLE
Dies on exception `Unexpected token t in JSON`

### ISSUE THREAD

**Issue by simonhac** [cflurin/homebridge-websocket#5]
(apologies that i've had very little experience with WS, so there's every chance that i'm doing something stupid.)

i'm using the `Simple WebSocket Client` to communicate with `homebridge-websocket`.
after connecting (successfully) to `ws://127.0.0.1:4050`, i send `{topic: "get", payload: {"name": "all"}}`.

the homebridge instance bails with the exception:
```
[5/1/2017, 8:34:12 PM] [websocket] client ip ::ffff:127.0.0.1 connected
  cbus:client rx event { time: '20170501-203419.950', code: 700, processed: false, message: 'cgate - Heartbeat.', type: 'event', raw: '#e# 20170501-203419.950 700 cgate - Heartbeat.' } +10s
  cbus:platform Heartbeat @ 20170501-203419.950 +1ms
undefined:1
{topic: "get", payload: {"name": "all"}}
 ^

SyntaxError: Unexpected token t in JSON at position 1
    at Object.parse (native)
    at Websocket.onMessage (/Users/simon/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-websocket/lib/websocket.js:71:18)
    at Websocket.message (/Users/simon/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-websocket/lib/websocket.js:51:12)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/simon/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-websocket/node_modules/ws/lib/WebSocket.js:816:10)
    at /Users/simon/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:477:18
    at /Users/simon/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:361:7
    at /Users/simon/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-websocket/node_modules/ws/lib/PerMessageDeflate.js:238:5
    at afterWrite (_stream_writable.js:388:3)
```

any advice welcome.

**Comment by simonhac** [comment]
same also happens when sending from `Dark WebSocket Terminal`.

(i'm just entering `{topic: "get", payload: {"name": "all"}}` -- nothing else.)

**Comment by cflurin** [comment]
try using apostrophes:
```sh
{"topic": "get", "payload": {"name": "all"}}
```

**Comment by simonhac** [comment]
thanks @cflurin -- there were no apostrophes in your sample comment. can you please clarify?

**Comment by cflurin** [comment]
Does it work with apostrophes?
I tested homebridge-websocket with node-red, node-red adds apostrophes automatically when missing.
If it works with apostrophes, I'll revise README.

**Comment by simonhac** [comment]
sorry, i don't know what you mean by apostrophes -- i know the ' symbol, but where do you intend for it to go? around the text or instead of the quotes or somewhere else?

**Comment by cflurin** [comment]
sorry, I mean quotes (" symbol) around "topic" and "payload":
```sh
{"topic": "get", "payload": {"name": "all"}}
```

**Comment by simonhac** [comment]
thanks @cflurin -- that works:
![image](https://cloud.githubusercontent.com/assets/20500649/25580045/b98721f2-2ec0-11e7-83b5-ec082f6b3dd7.png)

can you suggest a more interesting query that shows off an interesting data stream? (i'll spend some more time over the next couple of days familiarising myself with WS and `homebridge-websocket`.)

can i suggest that it might be a good idea to harden `homebridge-websocket` against bad input?

**Comment by cflurin** [comment]
- Ok, I've revised README.

- I'd try to add an accessory and get/set the value. I generally use node-red for testing but for my home automation I use node-red and [homebridge-mqtt](https://github.com/cflurin/homebridge-mqtt).

- Actually `homebridge-mqtt` has better error handling (e.g. "invalid JSON format").
I've planed a new `homebridge-websocket` version based on `homebridge-mvc`.

**Comment by simonhac** [comment]
thanks @cflurin -- i really appreciate your help. (i'll check out `homebridge-mqtt` and `homebridge-mvc`.)
