### ISSUE TITLE
No accessories detected

### ISSUE THREAD

**Issue by MatsA** [cflurin/homebridge-websocket#6]
Been running Homebridge for some Years, post here https://pysselilivet.blogspot.com/2016/11/homekit-z-wave-telldus-live.html, and just discovered Your plugin but as said in another post none of the already registered accessories is detected and no 
accessories is stored in the file /.homebridge/accesories/cacheAccessories. But Homebridge is working !
So empty answer on a {"topic": "get", "payload": {"name": "all"}}
No problem to "add" an accessorie and then the  added accessorie appears in the {"topic": "get", "payload": {"name": "all"}}. Any ideas ?

**Comment by cflurin** [comment]
You can only get the accessories added via homebridge-websocket.
It is the same as the homebridge-mqtt plugin. Have a look here:

https://github.com/cflurin/homebridge-mqtt/issues/8

**Comment by MatsA** [comment]
Hi and thanks for very quick support, appreciated !

Done a PR so coming users have a clear info of what the plugin can do.

Thanks, Mats
